"""add_index

Revision ID: 37fe47186db2
Revises: e8b12ba52665
Create Date: 2021-01-27 08:34:25.555819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fe47186db2'
down_revision = 'e8b12ba52665'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_lccs_class_mappings_source_class_id'), 'class_mappings', ['source_class_id'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_class_mappings_target_class_id'), 'class_mappings', ['target_class_id'], unique=False, schema='lccs')
    op.add_column('class_systems', sa.Column('title', sa.String(length=255), nullable=False), schema='lccs')
    op.create_unique_constraint(op.f('class_systems_name_key'), 'class_systems', ['name', 'version'], schema='lccs')
    op.create_index(op.f('idx_lccs_class_systems_name'), 'class_systems', ['name'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_class_system_id'), 'classes', ['class_system_id'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_code'), 'classes', ['code'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_classes_name'), 'classes', ['name'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_style_formats_name'), 'style_formats', ['name'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_styles_class_system_id'), 'styles', ['class_system_id'], unique=False, schema='lccs')
    op.create_index(op.f('idx_lccs_styles_style_format_id'), 'styles', ['style_format_id'], unique=False, schema='lccs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_lccs_styles_style_format_id'), table_name='styles', schema='lccs')
    op.drop_index(op.f('idx_lccs_styles_class_system_id'), table_name='styles', schema='lccs')
    op.drop_index(op.f('idx_lccs_style_formats_name'), table_name='style_formats', schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_name'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_code'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_classes_class_system_id'), table_name='classes', schema='lccs')
    op.drop_index(op.f('idx_lccs_class_systems_name'), table_name='class_systems', schema='lccs')
    op.drop_constraint(op.f('class_systems_name_key'), 'class_systems', schema='lccs', type_='unique')
    op.drop_column('class_systems', 'title', schema='lccs')
    op.drop_index(op.f('idx_lccs_class_mappings_target_class_id'), table_name='class_mappings', schema='lccs')
    op.drop_index(op.f('idx_lccs_class_mappings_source_class_id'), table_name='class_mappings', schema='lccs')
    # ### end Alembic commands ###
